# Generated by Django 2.1.4 on 2019-01-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name': 'Категория вакансии', 'verbose_name_plural': 'Категории вакансий'},
        ),
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(blank=True, default=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(blank=True, default=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(upload_to='jobs_images/'),
        ),
    ]
