# Generated by Django 2.1.4 on 2019-02-15 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190110_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobCategory', verbose_name='Категория вакансии'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default=True, null=True, verbose_name='Полное описание вакансии'),
        ),
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(blank=True, default=True, max_length=128, null=True, verbose_name='Наличие образования'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(blank=True, default=True, max_length=512, null=True, verbose_name='Наименование вакансии'),
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.DecimalField(decimal_places=0, default=True, max_digits=15, verbose_name='Оплата труда'),
        ),
        migrations.AlterField(
            model_name='job',
            name='short_description',
            field=models.TextField(blank=True, default=None, max_length=50, null=True, verbose_name='Краткое описание вакансии'),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(blank=True, default=True, max_length=128, null=True, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='Job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job', verbose_name='Категория вакансии'),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(upload_to='jobs_images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главная'),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования'),
        ),
    ]
